import { useLocale } from "@/components/i18n/locale-provider";
import type { Interest } from "@/lib/contact";
import { site } from "@/lib/site";

const { team } = site;

const en = {
  season: "Season",
  goingToPress: "Going to press",
  coverLines: {
    timeline: "From last place to alliance captain",
    garage: (count: string) => `The garage: ${count} robots and a locked door`,
    backers: "The companies behind the team",
    contact: "Letters: write to us",
  },
  robotIssue: "The robotics issue",
  vol: "Vol.",
  coverStory: "Cover story",
  weAreBack: ["We are ", "back."],
  standfirst: `Team ${team.number} has built robots in Döşemealtı since ${team.rookieYear}, as Imperium and Lycia before it became Mediterra. Last April it captained an alliance in Ankara.`,
  writeToUs: "Write to us",
  support: "Support the team",
  fig1: "Fig. 1",
  illustration: "Illustration",
  chapter: "Chapter",
  regionals: (count: string) => `${count} regionals`,
  timelineNote:
    "Every event since the rookie season, from FIRST’s own records. The name went from Imperium to Lycia and back again before it became Mediterra.",
  fig2: "Fig. 2 · Where we finished",
  embargoed: "Embargoed",
  plate: "Plate",
  as: (name: string) => `as ${name}`,
  withheld: (game: string) => `${game}, withheld until kickoff`,
  revealed: "The game is revealed on 9 January 2027.",
  garage: "The garage",
  garageNote: (plate: string, game: string) =>
    `One robot for every season we competed. The plates are illustrations of a typical machine for each year’s game, not portraits of ours. Plate ${plate} stays covered until ${game} is revealed.`,
  youllBuild: "The one you’ll help build.",
  joinTeam: "Join the team",
  seasonGroup: (year: number) => `The ${year} season`,
  earlier: "Earlier seasons",
  companies: ["The companies", "behind the team"],
  backersNote: `${team.school} has backed the team every season since ${team.rookieYear}. The companies below have backed it too, in the years shown.`,
  madePossible: "Colophon · made possible by",
  nextIssue: "Put your name in the next issue",
  colophon: "Colophon",
  colophonNote: `Set in Instrument Serif and Newsreader. Results from FIRST’s event records. Published from ${team.city}.`,
  backToCover: "Back to the cover",
  letters: "Letters",
  writeTo: ["Write to ", "us"],
  lettersNote: "Fill in the blanks. Someone on the team reads every letter.",
  dear: `Dear ${team.number},`,
  myNameIs: "My name is",
  writeBackAt: ", and you can write back to me at",
  afterEmail: ".",
  likeBefore: "I’d like to ",
  likeAfter: ".",
  phrase: {
    crew: "join the team",
    sponsor: "sponsor the team",
    mentor: "mentor the team",
    other: "talk about something else",
  } as Record<Interest, string>,
  namePlaceholder: "your name",
  emailPlaceholder: "you@example.com",
  nameLabel: "Your name",
  emailLabel: "Your email",
  interestLabel: "What you’d like to do",
  messageLabel: "Your message",
  messagePlaceholder: "The rest of the letter…",
  signed: "— Signed, and sent from the website",
  posting: "Posting…",
  send: "Send the letter →",
};

const tr: typeof en = {
  season: "Sezon",
  goingToPress: "Baskıya gidiyor",
  coverLines: {
    timeline: "Sonunculuktan ittifak kaptanlığına",
    garage: (count: string) => `Garaj: ${count} robot ve kilitli bir kapı`,
    backers: "Takımın arkasındaki şirketler",
    contact: "Mektuplar: bize yazın",
  },
  robotIssue: "Robotik sayısı",
  vol: "Cilt",
  coverStory: "Kapak konusu",
  weAreBack: ["Geri ", "döndük."],
  standfirst: `${team.number} numaralı takım ${team.rookieYear}'den beri Döşemealtı'nda robot yapıyor; Mediterra olmadan önce Imperium ve Lycia adlarını taşıdı. Geçen nisan Ankara'da bir ittifakın kaptanıydı.`,
  writeToUs: "Bize yazın",
  support: "Takımı destekleyin",
  fig1: "Şekil 1",
  illustration: "Çizim",
  chapter: "Bölüm",
  regionals: (count: string) => `${count} regional`,
  timelineNote:
    "Çaylak sezonundan bu yana her yarışma, FIRST'ün kendi kayıtlarından. İsim, Mediterra olmadan önce Imperium'dan Lycia'ya, sonra yeniden Imperium'a döndü.",
  fig2: "Şekil 2 · Nerede bitirdik",
  embargoed: "Ambargolu",
  plate: "Levha",
  as: (name: string) => `${name} adıyla`,
  withheld: (game: string) => `${game}, kickoff'a kadar gizli`,
  revealed: "Oyun 9 Ocak 2027'de açıklanıyor.",
  garage: "Garaj",
  garageNote: (plate: string, game: string) =>
    `Yarıştığımız her sezon için bir robot. Levhalar her yılın oyunu için tipik bir makinenin çizimi, bizimkilerin portresi değil. Levha ${plate}, ${game} açıklanana kadar örtülü kalıyor.`,
  youllBuild: "Yapımına senin de katılacağın robot.",
  joinTeam: "Takıma katıl",
  seasonGroup: (year: number) => `${year} sezonu`,
  earlier: "Önceki sezonlar",
  companies: ["Takımın arkasındaki", "şirketler"],
  backersNote: `${team.school} takımı ${team.rookieYear}'den beri her sezon destekledi. Aşağıdaki şirketler de gösterilen yıllarda destek verdi.`,
  madePossible: "Künye · katkılarıyla",
  nextIssue: "Adınızı bir sonraki sayıya yazdırın",
  colophon: "Künye",
  colophonNote:
    "Instrument Serif ve Newsreader ile dizildi. Sonuçlar FIRST'ün yarışma kayıtlarından. Döşemealtı, Antalya'dan yayımlandı.",
  backToCover: "Kapağa dön",
  letters: "Mektuplar",
  writeTo: ["Bize ", "yazın"],
  lettersNote: "Boşlukları doldurun. Takımdan biri her mektubu okuyor.",
  dear: `Sevgili ${team.number},`,
  myNameIs: "Benim adım",
  writeBackAt: "; bana",
  afterEmail: " adresinden yazabilirsiniz.",
  likeBefore: "",
  likeAfter: " istiyorum.",
  phrase: {
    crew: "takıma katılmak",
    sponsor: "takıma sponsor olmak",
    mentor: "takıma mentorluk yapmak",
    other: "başka bir konuda konuşmak",
  },
  namePlaceholder: "adınız",
  emailPlaceholder: "siz@ornek.com",
  nameLabel: "Adınız",
  emailLabel: "E-posta adresiniz",
  interestLabel: "Ne yapmak istediğiniz",
  messageLabel: "Mesajınız",
  messagePlaceholder: "Mektubun devamı…",
  signed: "— İmza: web sitesinden gönderildi",
  posting: "Gönderiliyor…",
  send: "Mektubu gönder →",
};

export function useCopy() {
  return useLocale() === "tr" ? tr : en;
}
