import { useLocale } from "@/components/i18n/locale-provider";
import type { TimelineKind } from "@/lib/content";
import { site } from "@/lib/site";

const { team } = site;

const en = {
  checks: ["FMS", "Driver station", "Robot"],
  connecting: "Connecting to field",
  match: "Match",
  loading: "loading",
  ready: "ready",
  red: "Red",
  blue: "Blue",
  cells: ["Days", "Hrs", "Min", "Sec"],
  buildOn: "Build season is on",
  kickoffIn: "Kickoff in",
  kickoffOn: `${team.season} kickoff: 9 January 2027`,
  lastResult: `${team.lastCompeted}: 7th of 33, Alliance 5 captain`,
  membership: "Membership closed",
  live: "On deck",
  seasonLabel: `${team.season} season`,
  qualification: `Qualification 01 · ${team.season} season`,
  headline: ["Next match ", String(team.season)],
  getInTouch: "Get in touch",
  sponsorUs: "Sponsor us",
  result: { legacy: "Played", latest: "Last season", next: "Up next" } as Record<TimelineKind, string>,
  matchLog: "Match log",
  regionals: (count: string) => `${count} regionals`,
  bestFinish: "Best qualification finish per season",
  cols: ["Season", "Result", "Summary"],
  unlocks: (game: string) => `${game} unlocks at kickoff`,
  unitSelect: "Unit select",
  illustration: "Illustration of a typical robot for this game",
  rows: ["Season", "Game", "Team name"],
  robotSelect: "Robot select",
  pickSeason: "Pick a season",
  locked: "Locked",
  partners: "Partners",
  presentedBy: "Past and present",
  partnersNote: `${team.school} has backed the team every season. These companies have too, in the years shown.`,
  becomePartner: "Become a partner",
  registration: "Contact",
  joinThe: ["Get in", "touch"],
  selectRole: "Select your role",
  name: "Name",
  namePlaceholder: "Your name",
  email: "Email",
  emailPlaceholder: "you@example.com",
  message: "Message",
  messagePlaceholder: "Tell us who you are and what you want to do",
  lockingIn: "Sending…",
  lockIn: "Send it →",
  privacyNote: "We use your name, email and message only to reply to you. Under 18? Ask a parent or teacher to write instead.",
  privacyLink: "Privacy notice",
};

const tr: typeof en = {
  checks: ["FMS", "Sürücü istasyonu", "Robot"],
  connecting: "Sahaya bağlanıyor",
  match: "Maç",
  loading: "yükleniyor",
  ready: "hazır",
  red: "Kırmızı",
  blue: "Mavi",
  cells: ["Gün", "Sa", "Dk", "Sn"],
  buildOn: "Yapım sezonu başladı",
  kickoffIn: "Kickoff'a kalan",
  kickoffOn: `${team.season} kickoff: 9 Ocak 2027`,
  lastResult: `${team.lastCompeted}: 33'te 7., 5. İttifak kaptanı`,
  membership: "Üye alımı kapalı",
  live: "Sırada",
  seasonLabel: `${team.season} sezonu`,
  qualification: `Sıralama 01 · ${team.season} sezonu`,
  headline: ["Sıradaki maç ", String(team.season)],
  getInTouch: "Bize yazın",
  sponsorUs: "Sponsor ol",
  result: { legacy: "Oynandı", latest: "Geçen sezon", next: "Sıradaki" },
  matchLog: "Maç kaydı",
  regionals: (count: string) => `${count} regional`,
  bestFinish: "Sezon başına en iyi sıralama derecesi",
  cols: ["Sezon", "Sonuç", "Özet"],
  unlocks: (game: string) => `${game} kickoff'ta açılıyor`,
  unitSelect: "Ünite seçimi",
  illustration: "Bu oyun için tipik bir robotun çizimi",
  rows: ["Sezon", "Oyun", "Takım adı"],
  robotSelect: "Robot seçimi",
  pickSeason: "Bir sezon seç",
  locked: "Kilitli",
  partners: "Destekçiler",
  presentedBy: "Destekçilerimiz",
  partnersNote: `${team.school} takımı her sezon destekledi. Bu şirketler de gösterilen yıllarda destek verdi.`,
  becomePartner: "Destekçi olun",
  registration: "İletişim",
  joinThe: ["Bize", "yazın"],
  selectRole: "Rolünü seç",
  name: "Ad",
  namePlaceholder: "Adınız",
  email: "E-posta",
  emailPlaceholder: "siz@ornek.com",
  message: "Mesaj",
  messagePlaceholder: "Kim olduğunuzu ve ne yapmak istediğinizi anlatın",
  lockingIn: "Gönderiliyor…",
  lockIn: "Gönder →",
  privacyNote: "Adınızı, e-postanızı ve mesajınızı yalnızca size yanıt vermek için kullanırız. 18 yaşından küçükseniz bize veliniz ya da öğretmeniniz yazsın.",
  privacyLink: "Aydınlatma metni",
};

export function useCopy() {
  return useLocale() === "tr" ? tr : en;
}
