import { useLocale } from "@/components/i18n/locale-provider";
import type { SectionId, TimelineKind } from "@/lib/content";
import { site } from "@/lib/site";

const { team } = site;

const en = {
  checks: ["FMS", "Driver station", "Robot"],
  connecting: "Connecting to field",
  match: "Match",
  loading: "loading",
  ready: "ready",
  nav: { timeline: "Match log", garage: "Robot select", backers: "Partners", contact: "Join" } as Record<
    Exclude<SectionId, "top">,
    string
  >,
  red: "Red",
  blue: "Blue",
  cells: ["Days", "Hrs", "Min", "Sec"],
  buildOn: "Build season is on",
  kickoffIn: "Kickoff in",
  lastResult: `${team.lastCompeted}: 7th of 33, Alliance 5 captain`,
  recruiting: "Recruiting",
  live: "Live",
  seasonLabel: `${team.season} season`,
  qualification: `Qualification 01 · ${team.season} season`,
  weAreBack: ["We are ", "back"],
  joinAlliance: "Join the alliance",
  sponsorUs: "Sponsor us",
  result: { legacy: "Played", latest: "Last season", next: "Up next" } as Record<TimelineKind, string>,
  matchLog: "Match log",
  regionals: (count: string) => `${count} regionals`,
  bestFinish: "Best qualification finish per season",
  cols: ["Season", "Result", "Summary"],
  unlocks: (game: string) => `${game} unlocks at kickoff`,
  unitSelect: "Unit select",
  illustration: "Illustration of a typical robot for this game",
  rows: ["Season", "Game", "Team name"],
  robotSelect: "Robot select",
  pickSeason: "Pick a season",
  locked: "Locked",
  partners: "Partners",
  presentedBy: "Presented by",
  partnersNote: `${team.school} has backed the team every season. These companies have too, in the years shown.`,
  becomePartner: "Become a partner",
  registration: "Registration",
  joinThe: ["Join the", "alliance"],
  selectRole: "Select your role",
  name: "Name",
  namePlaceholder: "Your name",
  email: "Email",
  emailPlaceholder: "you@example.com",
  message: "Message",
  messagePlaceholder: "Tell us who you are and what you want to do",
  lockingIn: "Locking in…",
  lockIn: "Lock in →",
};

const tr: typeof en = {
  checks: ["FMS", "Sürücü istasyonu", "Robot"],
  connecting: "Sahaya bağlanıyor",
  match: "Maç",
  loading: "yükleniyor",
  ready: "hazır",
  nav: { timeline: "Maç kaydı", garage: "Robot seçimi", backers: "Destekçiler", contact: "Katıl" },
  red: "Kırmızı",
  blue: "Mavi",
  cells: ["Gün", "Sa", "Dk", "Sn"],
  buildOn: "Yapım sezonu başladı",
  kickoffIn: "Kickoff'a kalan",
  lastResult: `${team.lastCompeted}: 33'te 7., 5. İttifak kaptanı`,
  recruiting: "Üye alımı",
  live: "Canlı",
  seasonLabel: `${team.season} sezonu`,
  qualification: `Sıralama 01 · ${team.season} sezonu`,
  weAreBack: ["Geri ", "döndük"],
  joinAlliance: "İttifaka katıl",
  sponsorUs: "Sponsor ol",
  result: { legacy: "Oynandı", latest: "Geçen sezon", next: "Sıradaki" },
  matchLog: "Maç kaydı",
  regionals: (count: string) => `${count} regional`,
  bestFinish: "Sezon başına en iyi sıralama derecesi",
  cols: ["Sezon", "Sonuç", "Özet"],
  unlocks: (game: string) => `${game} kickoff'ta açılıyor`,
  unitSelect: "Ünite seçimi",
  illustration: "Bu oyun için tipik bir robotun çizimi",
  rows: ["Sezon", "Oyun", "Takım adı"],
  robotSelect: "Robot seçimi",
  pickSeason: "Bir sezon seç",
  locked: "Kilitli",
  partners: "Destekçiler",
  presentedBy: "Katkılarıyla",
  partnersNote: `${team.school} takımı her sezon destekledi. Bu şirketler de gösterilen yıllarda destek verdi.`,
  becomePartner: "Destekçi olun",
  registration: "Kayıt",
  joinThe: ["İttifaka", "katıl"],
  selectRole: "Rolünü seç",
  name: "Ad",
  namePlaceholder: "Adınız",
  email: "E-posta",
  emailPlaceholder: "siz@ornek.com",
  message: "Mesaj",
  messagePlaceholder: "Kim olduğunuzu ve ne yapmak istediğinizi anlatın",
  lockingIn: "Gönderiliyor…",
  lockIn: "Onayla →",
};

export function useCopy() {
  return useLocale() === "tr" ? tr : en;
}
